### PR TITLE
Promote Canary Upgrade and Revision Tags to Beta

### PR DESCRIPTION
**Pull request by kfaseela**
Signed-off-by: Faseela K <faseela.k@est.tech>

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM! This is the only reasonable way to run Istio in production and has been used by users in prod for well over a year with strong feedback. Well overdue, thanks for pushing this past the finish like @kfaseela

**Comment by howardjohn** [comment]
Oops, thought this was supposed to have 2 approvals before merge. I guess not. fyi @istio/technical-oversight-committee  if anyone has concerns

**Comment by ericvn** [comment]
Looks good to me as well.

**Comment by linsun** [comment]
@kfaseela thanks for pushing this!! My only concern is the doc is not tested: https://istio.io/latest/docs/setup/upgrade/canary/

IIRC, we require all beta feature to be tested in our docs.

**Comment by kfaseela** [comment]
> @kfaseela thanks for pushing this!! My only concern is the doc is not tested: https://istio.io/latest/docs/setup/upgrade/canary/
> 
> IIRC, we require all beta feature to be tested in our docs.

Hello @linsun : As part of the promotion, doc tests were added. please see https://preliminary.istio.io/latest/docs/setup/upgrade/canary/

**Comment by linsun** [comment]
Very nice @kfaseela!

**Pull request merged**
