### PR TITLE
Promote dual-stack to Alpha

### PR DESCRIPTION
**Pull request by kfaseela**
Based on the discussion and issues tracked under: https://github.com/istio/istio/issues/47998

### CODE REVIEW

**Comment by kfaseela** [comment]
cc @whitneygriffith @leosarra

**Comment by keithmattix** [comment]
Hmm we should probably fix the schema validation test

**Comment by kfaseela** [comment]
> Hmm we should probably fix the schema validation test

point me to the issue?

**Comment by kfaseela** [comment]
@whitneygriffith @craigbox was this PR not on time for 1.23? Wondering why the feature status page still shows dualstack as experimental

**Comment by kfaseela** [comment]
> @whitneygriffith @craigbox was this PR not on time for 1.23? Wondering why the feature status page still shows dualstack as experimental

Looks like this will make it only in 1.24, even all the fixes we did has not fully been available in 1.23.. so all is good

**Pull request merged**
