### PR TITLE
promote Telemetry API to alpha

### PR DESCRIPTION
**Pull request by zirain**

### CODE REVIEW

**Comment by ericvn** [comment]
Can you also make sure https://github.com/istio/enhancements/blob/master/features/telemetry_api.md is filled out completely for Alpha.

**Comment by ericvn** [comment]
> looks like we need a TOC review for Telemetry API Alpha.

Yes, which is why I recommend that the form be updated so it can be reviewed.

**Review by howardjohn — COMMENTED** [review]
LGTM

**Review by lei-tang — APPROVED** [review]

**Review by linsun — COMMENTED** [review]
LGTM

Are we planning to add some tests for istio.io? https://preliminary.istio.io/latest/docs/tasks/observability/telemetry/

Would definitely want to see that before moving to the next stage.

**Comment by linsun** [comment]
NM, just saw https://github.com/istio/istio.io/pull/12973, nice!

**Comment by zirain** [comment]
also https://github.com/istio/istio.io/pull/12951

**Comment by ericvn** [comment]
@zirain And a LGTM from me as well, so 4 of 6 from the TOC meeting.

Would you please update the checkmarks showing you have TOC approval and you are updating the features.yaml in the PR so that can be checked as well. Then we can merge.

**Comment by zirain** [comment]
> @zirain And a LGTM from me as well, so 4 of 6 from the TOC meeting.
> 
> Would you please update the checkmarks showing you have TOC approval and you are updating the features.yaml in the PR so that can be checked as well. Then we can merge.

done!

**Review by ericvn — APPROVED** [review]
Thanks. Four TOC approvals at this point.

**Pull request merged**
