### PR TITLE
Add feature page for Prometheus Integration [Stable]

### PR DESCRIPTION
**Pull request by johnma14**

### CODE REVIEW

**Comment by johnma14** [comment]
@douglas-reid Could you take a look at this feature page for Prometheus Integration. I am creating feature pages for existing features and have been trying to attach the design docs and fill the checklist but there are some features I could not find much information about. Whenever you have some time, could you take a look at the checklist for the stable feature list since this one is marked stable: https://istio.io/latest/about/feature-stages/#observability. Thanks.

**Comment by douglas-reid** [comment]
There aren't too many design docs around Prometheus Integration. It has been there since 0.1 with very little change. I believe the one doc you linked in there is probably the only real design doc of merit at this point.

Prom integration is already documented in a fashion here: https://istio.io/latest/docs/ops/integrations/prometheus/

The metrics themselves are described on the website: https://istio.io/latest/docs/reference/config/metrics/
We have various Tasks documenting prometheus-based metrics interactions, including: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/ and https://istio.io/latest/docs/tasks/observability/metrics/querying-metrics/

As for perf numbers, prometheus is included in the analysis here: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/. We also know of no major issues with the Prometheus integration at the moment. I believe it is safe to check those boxes.

Prom integration pre-dates any sort of supportability review group, so I don't know how to evaluate checking that box, but the WG did approve it as stable.

**Comment by johnma14** [comment]
Thanks @douglas-reid. Appreciate you taking the time to review this and share your thoughts. I will incorporate this into this feature page and push another change. At that point, if you can review it one last time I think it will be good to be merged if it looks good to you. Thank you.

**Comment by brian-avery** [comment]
@douglas-reid gentle reminder. Can you please review?

**Comment by johnma14** [comment]
@douglas-reid gentle reminder for a quick review. Thank you.

**Pull request closed without merging**
